name: Demo Workflow

on: [workflow_dispatch]

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello volocopter!"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
