name: GitHub Actions Demo

# Controls when the workflow will run
on: CI
  # Triggers the workflow on push or pull
  push:
      branches:
      - main
      - release/*
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello volocopter DevOps Team and Dev Team!"
